const books = [
    {
        id: 1,
        name: "To Kill a Mockingbird",
        author: "Harper Lee",
        description: "A novel about the serious issues of rape and racial inequality.",
        publishDate: "1960-07-11",
        isbn: "978-0061120084",
        language: "English",
        categories: ["Fiction", "Classics", "Historical"],
        rating: 4.8,
        img: "https://example.com/tokillamockingbird.jpg",
        isFavorite: false,
        isRead: false,
    },
    {
        id: 2,
        name: "1984",
        author: "George Orwell",
        description: "A dystopian social science fiction novel and cautionary tale about the future.",
        publishDate: "1949-06-08",
        isbn: "978-0451524935",
        language: "English",
        categories: ["Fiction", "Classics", "Dystopian"],
        rating: 4.6,
        img: "https://example.com/1984.jpg",
        isFavorite: true,
        isRead: true,
    },
    {
        id: 3,
        name: "Pride and Prejudice",
        author: "Jane Austen",
        description: "A romantic novel of manners that depicts the British landed gentry of the early 19th century.",
        publishDate: "1813-01-28",
        isbn: "978-1503290563",
        language: "English",
        categories: ["Fiction", "Romance", "Classics"],
        rating: 4.5,
        img: "https://example.com/prideandprejudice.jpg",
        isFavorite: false,
        isRead: false,
    },
    {
        id: 4,
        name: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        description: "A novel that explores themes of wealth, excess, and the American dream during the Jazz Age.",
        publishDate: "1925-04-10",
        isbn: "978-0743273565",
        language: "English",
        categories: ["Fiction", "Classics", "American Literature"],
        rating: 4.4,
        img: "https://example.com/thegreatgatsby.jpg",
        isFavorite: false,
        isRead: false,
    },
    {
        id: 5,
        name: "The Catcher in the Rye",
        author: "J.D. Salinger",
        description: "A story about teenage alienation and the loss of innocence in the modern world.",
        publishDate: "1951-07-16",
        isbn: "978-0316769488",
        language: "English",
        categories: ["Fiction", "Classics", "Young Adult"],
        rating: 4.0,
        img: "https://example.com/thecatcherintherye.jpg",
        isFavorite: false,
        isRead: false,
    },
    {
        id: 6,
        name: "Moby-Dick",
        author: "Herman Melville",
        description: "The narrative of Captain Ahab's obsessive quest to kill the white whale, Moby-Dick.",
        publishDate: "1851-10-18",
        isbn: "978-1503280786",
        language: "English",
        categories: ["Fiction", "Classics", "Adventure"],
        rating: 3.8,
        img: "https://example.com/mobydick.jpg",
        isFavorite: false,
        isRead: false,
    },
    {
        id: 7,
        name: "The Hobbit",
        author: "J.R.R. Tolkien",
        description: "A fantasy novel that follows the quest of Bilbo Baggins to win a share of the treasure guarded by a dragon.",
        publishDate: "1937-09-21",
        isbn: "978-0547928227",
        language: "English",
        categories: ["Fiction", "Fantasy", "Classics"],
        rating: 4.7,
        img: "https://example.com/thehobbit.jpg",
        isFavorite: true,
        isRead: true,
    },
    {
        id: 8,
        name: "War and Peace",
        author: "Leo Tolstoy",
        description: "A novel that chronicles the history of the French invasion of Russia through the stories of five aristocratic families.",
        publishDate: "1869-01-01",
        isbn: "978-0199232765",
        language: "English",
        categories: ["Fiction", "Historical", "Classics"],
        rating: 4.3,
        img: "https://example.com/warandpeace.jpg",
        isFavorite: false,
        isRead: false,
    },
    {
        id: 9,
        name: "The Brothers Karamazov",
        author: "Fyodor Dostoevsky",
        description: "A passionate philosophical novel that enters deeply into questions of God, free will, and morality.",
        publishDate: "1880-01-01",
        isbn: "978-0374528379",
        language: "English",
        categories: ["Fiction", "Classics", "Philosophy"],
        rating: 4.6,
        img: "https://example.com/thebrotherskaramazov.jpg",
        isFavorite: false,
        isRead: true,
    },
    {
        id: 10,
        name: "The Alchemist",
        author: "Paulo Coelho",
        description: "A novel about the journey of a young shepherd in search of his personal legend.",
        publishDate: "1988-04-01",
        isbn: "978-0061122415",
        language: "English",
        categories: ["Fiction", "Philosophy", "Adventure"],
        rating: 4.7,
        img: "https://example.com/thealchemist.jpg",
        isFavorite: true,
        isRead: false,
    }
];
