const books = [
  {
    id: 0,
    name: "The Design Of Books",
    author: "Debbie Berne",
    description:
      "The Design of Books is a classic book by Adrian Wilson that explores the principles and history of book design. It provides insights into typography, page layout, cover design, and the aesthetics of book production, combining both practical advice and historical context.",
    publishDate: "1960-07-11",
    isbn: "978-0061120084",
    language: "English",
    categories: ["Fiction", "Classics", "Historical"],
    rating: 4.8,
    img: "/view/assets/img/books/book-1.jpg",
    isFavorite: false,
    isRead: false,
  },
  {
    id: 1,
    name: "To Kill a Mockingbird",
    author: "Harper Lee",
    description:
      "A novel about the serious issues of rape and racial inequality.",
    publishDate: "1960-07-11",
    isbn: "978-0061120084",
    language: "English",
    categories: ["Fiction", "Classics", "Historical"],
    rating: 4.8,
    img: "/view/assets/img/books/tokillmocking.jpg",
    isFavorite: false,
    isRead: false,
  },
  {
    id: 2,
    name: "1984",
    author: "George Orwell",
    description:
      "A dystopian social science fiction novel and cautionary tale about the future.",
    publishDate: "1949-06-08",
    isbn: "978-0451524935",
    language: "English",
    categories: ["Fiction", "Classics", "Dystopian"],
    rating: 4.6,
    img: "/view/assets/img/books/1984.jpg",
    isFavorite: true,
    isRead: true,
  },
  {
    id: 3,
    name: "Pride and Prejudice",
    author: "Jane Austen",
    description:
      "A romantic novel of manners that depicts the British landed gentry of the early 19th century.",
    publishDate: "1813-01-28",
    isbn: "978-1503290563",
    language: "English",
    categories: ["Fiction", "Romance", "Classics"],
    rating: 4.5,
    img: "/view/assets/img/books/prideandprejudice.jpg",
    isFavorite: false,
    isRead: false,
  },
  {
    id: 4,
    name: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description:
      "A novel that explores themes of wealth, excess, and the American dream during the Jazz Age.",
    publishDate: "1925-04-10",
    isbn: "978-0743273565",
    language: "English",
    categories: ["Fiction", "Classics", "American Literature"],
    rating: 4.4,
    img: "/view/assets/img/books/thegreatgatsby.jpg",
    isFavorite: false,
    isRead: false,
  },
  {
    id: 5,
    name: "The Catcher in the Rye",
    author: "J.D. Salinger",
    description:
      "A story about teenage alienation and the loss of innocence in the modern world.",
    publishDate: "1951-07-16",
    isbn: "978-0316769488",
    language: "English",
    categories: ["Fiction", "Classics", "Young Adult"],
    rating: 4.0,
    img: "/view/assets/img/books/thecatcherintherye.jpg",
    isFavorite: false,
    isRead: false,
  },
  {
    id: 6,
    name: "Moby-Dick",
    author: "Herman Melville",
    description:
      "The narrative of Captain Ahab's obsessive quest to kill the white whale, Moby-Dick.",
    publishDate: "1851-10-18",
    isbn: "978-1503280786",
    language: "English",
    categories: ["Fiction", "Classics", "Adventure"],
    rating: 3.8,
    img: "/view/assets/img/books/mobydick.jpg",
    isFavorite: false,
    isRead: false,
  },
  {
    id: 7,
    name: "The Hobbit",
    author: "J.R.R. Tolkien",
    description:
      "A fantasy novel that follows the quest of Bilbo Baggins to win a share of the treasure guarded by a dragon.",
    publishDate: "1937-09-21",
    isbn: "978-0547928227",
    language: "English",
    categories: ["Fiction", "Fantasy", "Classics"],
    rating: 4.7,
    img: "/view/assets/img/books/thehobbit.jpg",
    isFavorite: true,
    isRead: true,
  },
  {
    id: 8,
    name: "War and Peace",
    author: "Leo Tolstoy",
    description:
      "A novel that chronicles the history of the French invasion of Russia through the stories of five aristocratic families.",
    publishDate: "1869-01-01",
    isbn: "978-0199232765",
    language: "English",
    categories: ["Fiction", "Historical", "Classics"],
    rating: 4.3,
    img: "/view/assets/img/books/warandpeace.jpg",
    isFavorite: false,
    isRead: false,
  },
  {
    id: 9,
    name: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    description:
      "A passionate philosophical novel that enters deeply into questions of God, free will, and morality.",
    publishDate: "1880-01-01",
    isbn: "978-0374528379",
    language: "English",
    categories: ["Fiction", "Classics", "Philosophy"],
    rating: 4.6,
    img: "/view/assets/img/books/thebrotherskaramazov.jpg",
    isFavorite: false,
    isRead: true,
  },
  {
    id: 10,
    name: "The Alchemist",
    author: "Paulo Coelho",
    description:
      "A novel about the journey of a young shepherd in search of his personal legend.",
    publishDate: "1988-04-01",
    isbn: "978-0061122415",
    language: "English",
    categories: ["Fiction", "Philosophy", "Adventure"],
    rating: 4.7,
    img: "/view/assets/img/books/thealchemist.jpg",
    isFavorite: true,
    isRead: false,
  },
  {
    id: 11,
    name: "The Divine Comedy",
    author: "Dante Alighieri",
    description:
      "An epic poem describing Dante’s journey through Hell, Purgatory, and Paradise.",
    publishDate: "1320-01-01",
    isbn: "978-0140448955",
    language: "English",
    categories: ["Classic", "Poetry", "Philosophy"],
    rating: 4.7,
    img: "/view/assets/img/books/divinecomedy.jpg",
    isFavorite: true,
    isRead: false,
  },
  {
    id: 12,
    name: "Les Misérables",
    author: "Victor Hugo",
    description:
      "A tale of love, justice, and redemption set in post-revolutionary France.",
    publishDate: "1862-04-03",
    isbn: "978-0451419439",
    language: "English",
    categories: ["Fiction", "Historical", "Classic"],
    rating: 4.8,
    img: "/view/assets/img/books/lesmiserables.jpg",
    isFavorite: false,
    isRead: true,
  },
  {
    id: 13,
    name: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    description:
      "A philosophical novel about the consequences of a life devoted to pleasure.",
    publishDate: "1890-06-20",
    isbn: "978-0141442464",
    language: "English",
    categories: ["Fiction", "Philosophy", "Classic"],
    rating: 4.5,
    img: "/view/assets/img/books/doriangray.jpg",
    isFavorite: true,
    isRead: true,
  },
  {
    id: 14,
    name: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    description:
      "An epic fantasy adventure across Middle-earth to destroy the One Ring.",
    publishDate: "1954-07-29",
    isbn: "978-0618640157",
    language: "English",
    categories: ["Fantasy", "Adventure", "Classic"],
    rating: 4.9,
    img: "/view/assets/img/books/lordoftherings.jpg",
    isFavorite: false,
    isRead: false,
  },
  {
    id: 15,
    name: "The Grapes of Wrath",
    author: "John Steinbeck",
    description:
      "A story of hardship and resilience during the Great Depression.",
    publishDate: "1939-04-14",
    isbn: "978-0143039433",
    language: "English",
    categories: ["Fiction", "Historical", "Classic"],
    rating: 4.6,
    img: "/view/assets/img/books/grapesofwrath.jpg",
    isFavorite: false,
    isRead: true,
  },
];
